plugins {
    id 'net.minecraftforge.gradle' version '[6.0.24,6.2)' apply false
}

tasks.register('clean', Delete) {
    delete rootProject.layout.buildDirectory
}

subprojects {
    apply plugin: 'java'
    java.toolchain.languageVersion = JavaLanguageVersion.of(17)

    tasks.withType(JavaCompile).configureEach {
        options.encoding = 'UTF-8'
        options.release = 17
    }

    tasks.withType(Javadoc).configureEach {
        enabled = false
    }
}

tasks.register('cleanOutJars', Delete) {
    group = 'dev-run'
    description = 'Cleans the out_jars folder.'
    delete layout.projectDirectory.dir('out_jars')
}

tasks.register('copyJars', Copy) {
    group = 'build'
    description = 'Copies the final Forge JAR file to the out_jars folder.'

    dependsOn('cleanOutJars', ':forge:build')

    from(project(':forge').layout.buildDirectory.dir('libs')) {
        include "*-${minecraft_version}-${version}.jar"
        exclude "*-sources.jar", "*-dev.jar", "*-shadow.jar", "*-all.jar", "*-sources-dev.jar", "*-javadoc.jar"
    }

    into layout.projectDirectory.dir('out_jars')
}

tasks.register('buildRelease') {
    group = 'dev-run'
    description = 'Cleans everything and generates the Forge JAR in the out_jars folder.'
    dependsOn 'clean', 'copyJars'
}

tasks.register('runClient') {
    group = 'dev-run'
    description = 'Run Forge client'
    dependsOn ':forge:Client'
}

tasks.register('runServer') {
    group = 'dev-run'
    description = 'Run Forge server'
    dependsOn ':forge:Server'
}
