# Important Notes:
# Every field you add must be added to the root build.gradle expandProps map.

# Project
version=1.2.0
group=com.javiluli.createpipeconnector
java_version=21

# Common
minecraft_version=1.21.1
mod_name=Create: Pipe Connector
mod_author=Javiluli
mod_id=createpipeconnector
license=MIT
credits=
description=Preview and place Create fluid pipe routes with anchors, pumps, casing, pipe styles, and optional progressive construction. Select a start point, guide the route around obstacles, and confirm the complete connection in one action.
minecraft_version_range=[1.21.1]
parchment_minecraft=1.21
parchment_version=2024.11.10

# NeoForge
neoforge_version=21.1.219
neoforge_loader_version_range=[4,)
neoforge_dependency_version_range=[21.1.218,21.2)

# Create
create_version=6.0.6-107
ponder_version=1.0.56
flywheel_version=1.0.0-9
registrate_version=MC1.21-1.3.0+62

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
