# Important Notes:
# Every field you add must be added to the root build.gradle expandProps map.

# Project
version=0.2.0-beta
group=com.javiluli.createpipeconnector
java_version=17

# Common
minecraft_version=1.20.1
mod_name=Create: Pipe Connector
mod_author=Javiluli
mod_id=createpipeconnector
license=MIT
credits=
description=Create: Pipe Connector is a beta Create addon for Minecraft 1.20.1 that connects Create fluid pipes through a valid route and shows a ghost preview before placing them.
minecraft_version_range=[1.20.1, 1.21)
neo_form_version=1.20.1-20230612.114412
parchment_minecraft=1.20.1
parchment_version=2023.09.03

# Forge
forge_version=47.4.20
forge_loader_version_range=[47,)

# Create
create_version=6.0.8-289
ponder_version=1.0.91
flywheel_version=1.0.5
registrate_version=MC1.20-1.3.3

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
